### ISSUE TITLE
nav-btn

### ISSUE THREAD

**Issue by mambax7** [angelorocha/xbootstrap#11]
We need to remove or change the alpha.png in:
.photo-nav-controls ul li.nav-btn{background:url(images/alpha.png); width:30px; font-size:1.5em;}

as currently it is too dark.

![image](https://cloud.githubusercontent.com/assets/613686/6552412/d8c98e5c-c61b-11e4-87b5-c52c4aef50a1.png)

**Comment by angelorocha** [comment]
Done.
